name: Setup Elasticsearch Infrastructure

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'dev'
        type: choice
        options:
        - dev
        - staging
        - prod
      region:
        description: 'AWS Region'
        required: true
        default: 'us-east-1'
        type: string

env:
  AWS_REGION: ${{ github.event.inputs.region || 'us-east-1' }}
  ENVIRONMENT: ${{ github.event.inputs.environment || 'dev' }}

jobs:
  setup-elasticsearch:
    name: Setup Elasticsearch Domain
    runs-on: ubuntu-latest
    environment: ${{ env.ENVIRONMENT }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
        
    - name: Setup CDK
      run: |
        npm install -g aws-cdk
        cdk --version
        
    - name: Bootstrap CDK (if needed)
      run: cdk bootstrap aws://${{ secrets.AWS_ACCOUNT_ID }}/${{ env.AWS_REGION }}
      
    - name: Deploy Elasticsearch Infrastructure
      run: |
        cdk deploy JobBoardElasticsearchStack-${{ env.ENVIRONMENT }} \
          --require-approval never \
          --context environment=${{ env.ENVIRONMENT }}
          
    - name: Get Elasticsearch Domain Info
      run: |
        DOMAIN_NAME="job-board-${{ env.ENVIRONMENT }}"
        DOMAIN_ENDPOINT=$(aws es describe-elasticsearch-domain \
          --domain-name $DOMAIN_NAME \
          --query 'DomainStatus.Endpoints.vpc' \
          --output text 2>/dev/null || echo "Domain not ready yet")
        echo "ELASTICSEARCH_ENDPOINT=$DOMAIN_ENDPOINT" >> $GITHUB_ENV
        
    - name: Comment deployment info
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `🔍 **Elasticsearch Infrastructure Deployed!**
          
          **Environment:** ${{ env.ENVIRONMENT }}
          **Region:** ${{ env.AWS_REGION }}
          **Domain Name:** job-board-${{ env.ENVIRONMENT }}
          **Endpoint:** ${{ env.ELASTICSEARCH_ENDPOINT || 'Initializing...' }}
          
          [View Elasticsearch Domain](https://console.aws.amazon.com/es/home?region=${{ env.AWS_REGION }}#domain:resource=job-board-${{ env.ENVIRONMENT }};action=dashboard)`
          })
      if: github.event_name == 'workflow_dispatch' 